WinnerOne-LETS/Backend

src/main/java/com/yanolja_final/domain/user/entity/User.java
- user 도메인 작업이 생각보다 오래 걸려 마이페이지 기능 구현 진행할 수 있도록 user 엔터티 먼저 올립니다!
- 추가 기능은 후에 따로 pr 예정
=> [refactor] User 엔터티

src/main/java/com/yanolja_final/domain/packages/exception/PackageNotFoundException.java, src/main/java/com/yanolja_final/domain/packages/repository/PackageRepository.java, src/main/java/com/yanolja_final/domain/packages/service/PackageService.java, src/main/java/com/yanolja_final/domain/user/exception/UserNotFoundException.java, src/main/java/com/yanolja_final/domain/user/service/UserService.java, src/main/java/com/yanolja_final/domain/wish/controller/WishController.java, src/main/java/com/yanolja_final/domain/wish/dto/request/WishRequest.java, src/main/java/com/yanolja_final/domain/wish/dto/response/WishListResponse.java, src/main/java/com/yanolja_final/domain/wish/entity/Wish.java, src/main/java/com/yanolja_final/domain/wish/exception/WishNotFoundException.java, src/main/java/com/yanolja_final/domain/wish/facade/WishFacade.java, src/main/java/com/yanolja_final/domain/wish/repository/WishRepository.java, src/main/java/com/yanolja_final/domain/wish/service/WishService.java, src/main/java/com/yanolja_final/global/exception/ErrorCode.java, src/main/java/com/yanolja_final/global/util/PaginationUtils.java, src/main/resources/application.yml
- hard delete 적용
- 실행 결과 테스트 완료했습니다.(request, response 값 모두 api 문서와 동일)
- package 값이 들어있어야 테스트 가능합니다.
- 페이지네이션 응답 유틸리티 추가 (PaginationUtils 참고)
=> [Feature] 찜 등록, 삭제, 조회 구현

src/main/java/com/yanolja_final/domain/user/dto/request/CreateUserRequest.java, src/main/java/com/yanolja_final/domain/user/dto/response/CreateUserResponse.java, src/main/java/com/yanolja_final/domain/user/entity/User.java, src/main/java/com/yanolja_final/domain/user/service/UserService.java
변경 사항:
- 기획 변경 사항에 맞춰 닉네임 기능을 삭제하였습니다.
=> [refactor] 닉네임 기능 삭제

src/main/java/com/yanolja_final/domain/wish/dto/response/WishListResponse.java
- 위시리스트 조회시 여러 개의 introImage 중 하나만 반환하도록 구현.
=> [Refactor] JPA Entity 변경으로 인한 API 테스트 및 수정

src/main/java/com/yanolja_final/domain/review/controller/ReviewController.java, src/main/java/com/yanolja_final/domain/review/dto/response/ReviewSummaryResponse.java, src/main/java/com/yanolja_final/domain/review/facade/ReviewFacade.java, src/main/java/com/yanolja_final/domain/review/repository/ReviewRepository.java, src/main/java/com/yanolja_final/domain/review/service/ReviewService.java, src/main/java/com/yanolja_final/global/config/security/SecurityConfig.java
- GET /v1/reviews/packages/{packageId}/list/summary
- GET /v1/reviews/packages/{packageId}/list
- 테스트 완료 했습니다.
=> [Feature] 패키지 별 리뷰 조회 구현

src/main/java/com/yanolja_final/domain/faq/controller/FaqController.java, src/main/java/com/yanolja_final/domain/faq/dto/request/RegisterFaqRequest.java, src/main/java/com/yanolja_final/domain/faq/dto/response/FaqResponse.java, src/main/java/com/yanolja_final/domain/faq/entity/Faq.java, src/main/java/com/yanolja_final/domain/faq/facade/FaqFacade.java, src/main/java/com/yanolja_final/domain/faq/repository/FaqRepository.java, src/main/java/com/yanolja_final/domain/faq/service/FaqService.java
01.08일 ERD 변경 이후 Faq Entity에서 작성하여 올리는 PR 입니다.
=> [Feature] POST /v1/faq 자주 묻는 질문 글 작성#74

src/main/java/com/yanolja_final/domain/faq/controller/FaqController.java, src/main/java/com/yanolja_final/domain/faq/dto/request/RegisterFaqRequest.java, src/main/java/com/yanolja_final/domain/faq/dto/response/FaqListResponse.java, src/main/java/com/yanolja_final/domain/faq/dto/response/FaqResponse.java, src/main/java/com/yanolja_final/domain/faq/entity/Faq.java, src/main/java/com/yanolja_final/domain/faq/facade/FaqFacade.java, src/main/java/com/yanolja_final/domain/faq/repository/FaqRepository.java, src/main/java/com/yanolja_final/domain/faq/service/FaqService.java
자주 묻는 질문 글 작성의 피드백 반영하여, String[] categories에 빈 여백을 정리하는 trim 추가
1/8일 이후 ERD 수정본의 Entity 바탕으로 코드 작성
=> [Feature] GET /v1/faq 자주 묻는 질문 글 목록 조회

src/main/java/com/yanolja_final/domain/faq/controller/FaqController.java, src/main/java/com/yanolja_final/domain/faq/exception/FaqNotFoundException.java, src/main/java/com/yanolja_final/domain/faq/facade/FaqFacade.java, src/main/java/com/yanolja_final/domain/faq/service/FaqService.java, src/main/java/com/yanolja_final/global/exception/ErrorCode.java
자주 묻는 질문 글 작성의 피드백 반영하여, String[] categories, String[] content 에 빈 여백을 정리하는 trim 추가
1/8일 이후 ERD 수정본의 Entity 바탕으로 코드 작성
=> [Feature] GET /v1/faq/{id} 자주 묻는 질문 상세보기 #73

src/main/java/com/yanolja_final/domain/advertisement/controller/AdvertisementController.java, src/main/java/com/yanolja_final/domain/advertisement/dto/response/AdListItemResponse.java, src/main/java/com/yanolja_final/domain/advertisement/entity/Advertisement.java, src/main/java/com/yanolja_final/domain/advertisement/facade/AdFacade.java, src/main/java/com/yanolja_final/domain/advertisement/repository/AdRepository.java, src/main/java/com/yanolja_final/domain/advertisement/service/AdService.java, src/main/java/com/yanolja_final/global/config/security/SecurityConfig.java
closes #109 
- GET /v1/advertisements 구현 완료
- Advertisement 엔티티에 imageUrl 필드가 빠져있어서 추가함
- Advertisement 관련 data.sql INSERT문 추가
=> [Feature] GET /v1/advertisements 광고구좌 목록 조회

src/main/java/com/yanolja_final/domain/user/controller/MyPageController.java, src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java, src/main/java/com/yanolja_final/domain/user/dto/response/MyPageResponse.java, src/main/java/com/yanolja_final/domain/user/entity/User.java, src/main/java/com/yanolja_final/domain/user/facade/MyPageFacade.java, src/main/java/com/yanolja_final/domain/user/service/MyPageService.java
PATCH를 활용 - Request에 요청된 필드의 값 중 null이 아닌 값에 한해서만 업데이트 하는 기능 추가
=> [Feature] PATCH v1/my/info #39 내 정보 수정

src/main/java/com/yanolja_final/domain/user/controller/MyPageController.java, src/main/java/com/yanolja_final/domain/user/facade/MyPageFacade.java, src/main/java/com/yanolja_final/domain/user/service/MyPageService.java
#ResponseDTO 부분 전부 Controller에서 처리되도록 수정 완료 (Service, Facade에서 제거 완료)
#(전)User객체 하나를 조회하는 데에 List를 사용했었음 -> JSON [] 형태 
==> 후 MyPageResponse 만 리턴 해주는 방향으로 수정 -> JSON { } 객체만 표시해주는 형태로 수정 완료]
#Branch base : feature/39(내 정보 수정)  <-  compare : feature/113(내 정보 조회)
=> [Feature] GET /v1/my/info #113 내 정보 조회

src/main/java/com/yanolja_final/domain/faq/controller/FaqController.java, src/main/java/com/yanolja_final/domain/faq/dto/response/FaqListResponse.java, src/main/java/com/yanolja_final/domain/faq/dto/response/FaqResponse.java, src/main/java/com/yanolja_final/domain/faq/facade/FaqFacade.java, src/main/java/com/yanolja_final/domain/faq/service/FaqService.java
ResponseDTO 가 Controller 에서만 사용될 수 있도록 Service, Facade, Controller의 로직 변경
Response Class의 fromFaq() -> from() 메서드 명 변경 및 불필요한 줄 바꿈 제거
=> [refactor] 자주 묻는 질문 Faq->ResponseDTO 전부 controller 에서만 사용하도록 수정

src/main/java/com/yanolja_final/domain/packages/controller/PackageController.java, src/main/java/com/yanolja_final/domain/packages/dto/response/MyInfoDto.java, src/main/java/com/yanolja_final/domain/packages/dto/response/PackageDateTimeDTO.java, src/main/java/com/yanolja_final/domain/packages/dto/response/PackageDetailResponse.java, src/main/java/com/yanolja_final/domain/packages/dto/response/PackagePriceDTO.java, src/main/java/com/yanolja_final/domain/packages/dto/response/PackageReservationDTO.java, src/main/java/com/yanolja_final/domain/packages/dto/response/PackageServiceItemDTO.java, src/main/java/com/yanolja_final/domain/packages/entity/Package.java, src/main/java/com/yanolja_final/domain/packages/entity/PackageDepartureOption.java, src/main/java/com/yanolja_final/domain/packages/entity/PackageImage.java, src/main/java/com/yanolja_final/domain/packages/entity/PackageIntroImage.java, src/main/java/com/yanolja_final/domain/packages/exception/AvailableDateNotFoundException.java, src/main/java/com/yanolja_final/domain/packages/facade/PackageFacade.java, src/main/java/com/yanolja_final/domain/packages/service/PackageService.java, src/main/java/com/yanolja_final/domain/review/entity/Review.java, src/main/java/com/yanolja_final/domain/review/repository/ReviewRepository.java, src/main/java/com/yanolja_final/domain/wish/entity/Wish.java, src/main/java/com/yanolja_final/domain/wish/repository/WishRepository.java, src/main/java/com/yanolja_final/domain/wish/service/WishService.java, src/main/java/com/yanolja_final/global/config/argumentresolver/LoginedUserIdArgumentResolver.java, src/main/java/com/yanolja_final/global/config/security/SecurityConfig.java, src/main/java/com/yanolja_final/global/exception/ErrorCode.java
closes #44 
- GET /v1/packages/{id} 패키지 상세페이지 조회 구현했습니다
- `@LoginedUserId` 비로그인 시 null 반환하도록 변경했습니다 (기존에는 예외 발생)
- 크롤링해 받아온 리뷰에 대한 SQL문을 뒤늦게 추가했습니다
- Review 엔티티의 구조가 크롤링 리뷰 데이터 형식에 맞지 않아서 맞게 수정했습니다
- Long packageId 필드 추가
- content 길이 200으로 확장
- order nullable=true로 변경, 그에 따른 reviewRepository.findReviewsByPackageId, findReviewsByPackageIdSummary 알맞게 수정
Response Body 풀버전
```json
{
"code": 200,
"data": {
"packageId": 24021616900,
"hashtags": [],
"departureDatetime": {
"date": "2024-01-21",
"dayOfWeek": "일",
"time": "21:10"
},
"endDatetime": {
"date": "2024-01-25",
"dayOfWeek": "목",
"time": "04:40"
},
"imageUrls": [
"https://tourimage.interpark.com/product/tour/00161/A50/500/A5018338_1_977.jpg",
"https://tourimage.interpark.com/product/tour/00161/A50/500/A5018338_2_820.jpg", …
```
=> [Feature] GET /v1/packages/{id} 패키지 상세페이지 조회

src/main/java/com/yanolja_final/domain/packages/controller/PackageController.java, src/main/java/com/yanolja_final/domain/packages/dto/response/PackageListItemResponse.java, src/main/java/com/yanolja_final/domain/packages/entity/Package.java, src/main/java/com/yanolja_final/domain/packages/facade/PackageFacade.java, src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
closes #120 
- GET /v1/packages 패키지 전체 목록 구현
- 기획 상 필요없는 API지만 프론트엔드분들이 필요할 것 같아 추가
- 현재 기준으로 Wish를 테스트하고 싶어도 packageId가 뭐뭐 있는지를 몰라서 테스트가 불가능함
```json
{
"code": 200,
"data": {
"data": [
{
"packageId": 24010917188,
"imageUrl": "https://tourimage.interpark.com/product/tour/00161/D10/1000/D1014582_1_637.jpg",
"nationName": "싱가포르",
"hashtags": [],
"minPrice": 1050000,
"lodgeDays": 4,
"tripDays": 6
},
{
"packageId": 24011017110,
"imageUrl": "https://tourimage.interpark.com/product/tour/00161/Q60/500/Q6010710_1_783.jpg",
"nationName": "일본",
"hashtags": [],
"minPrice": 1630000,
"lodgeDays": 3,
"tripDays": 4
},
{
"packageId": 24011117432,
"imageUrl": "https://tourimage.interpark.com/product/tour/00161/D10/1000/D1014578_1_927.jpg",
"nationName": "싱가포르",
"hashtags": [],
"minPrice": 1440000, …
```
=> [feat] GET /v1/packages 패키지 전체 목록 구현

src/main/java/com/yanolja_final/global/config/security/SecurityConfig.java
=> [fix] Cors 설정

src/main/java/com/yanolja_final/domain/packages/controller/PackageController.java, src/main/java/com/yanolja_final/domain/packages/controller/PackageScheduleResponse.java, src/main/java/com/yanolja_final/domain/packages/dto/response/PackageScheduleResponse.java, src/main/java/com/yanolja_final/domain/packages/facade/PackageFacade.java, src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
- GET /v1/packages/{id}/schedules 일정 목록 구현
```json
{
"code": 200,
"data": [
{
"day": 1,
"schedule": [
"3층(출발층)에서 인솔자 미팅 (개별 연락 드립니다.)",
"[KE901] 인천 출발 (비행시간: 약14시간 15분)",
"파리 도착",
"호텔 투숙"
],
"breakfast": "불포함",
"lunch": "기내식",
"dinner": "기내식"
},
{
"day": 2,
"schedule": [
"호텔 조식 후",
"세계 문화유산이 모인 보물창고이자 세계 3대 박물관 중 한곳인 루브르 박물관",
"언제 보아도 어디서 보아도 낭만이 가득한 로맨틱한 파리Paris",
"호텔 투숙"
],
"breakfast": "호텔식",
"lunch": "현지식",
"dinner": "한식"
},
{
"day": 3,
"schedule": [
"호텔 조식 후",
"세계에서 가장 화려한 베르사유Versaiilles 궁전(내부)",
"낭만이 가득한 로맨틱한 파리 Paris",
"호텔 투숙"
],
"breakfast": "호텔식",
"lunch": "현지식",
"dinner": "한식"
},
{
"day": 4,
"schedule": [
"호텔 조식 후",
"[TGV] 파리 출발 (소요시간: 약3시간)",
"벨포트 도착 (도착지는 뮬루즈 등으로 변경 될 수 있습니다)",
"아름다운 청정 호수 도시 루체른Luzern (벨포트→루체른: 약 3시간)",
"유명한 린트초콜릿의 모든 것 초콜릿박물관 (Lindt Home of Chocolet)",
"호텔 …
```
=> [feat] GET /v1/packages/{id}/schedules 일정 목록 구현

src/main/java/com/yanolja_final/domain/packages/controller/PackageController.java, src/main/java/com/yanolja_final/domain/packages/dto/response/PackageAvailableDateResponse.java, src/main/java/com/yanolja_final/domain/packages/entity/PackageDepartureOption.java, src/main/java/com/yanolja_final/domain/packages/facade/PackageFacade.java
- GET /v1/packages/{id}/available-dates 예약가능한 출발일 구현
```json
{
"code": 200,
"data": [
{
"availableDateId": 12503,
"date": "2024-01-20",
"adultPrice": 3799000,
"lodgeDays": 8,
"tripDays": 10
},
{
"availableDateId": 12504,
"date": "2024-01-27",
"adultPrice": 3799000,
"lodgeDays": 8,
"tripDays": 10
},
{
"availableDateId": 12505,
"date": "2024-01-28",
"adultPrice": 3799000,
"lodgeDays": 8,
"tripDays": 10
},
{
"availableDateId": 12506,
"date": "2024-02-03",
"adultPrice": 3799000,
"lodgeDays": 8,
"tripDays": 10
},
{
"availableDateId": 12507,
"date": "2024-02-10",
"adultPrice": 3799000,
"lodgeDays": 8,
"tripDays": 10
},
{
"availableDateId": 12508,
"date": "2024-02-17",
"adultPrice": 3799000,
"lodgeDays": 8,
"tripDays": 10
},
{
"availableDateId": 12509,
"date": "2024-02-24",
"adultPrice": …
```
=> [feat] GET /v1/packages/{id}/available-dates 예약가능한 출발일 구현

src/main/java/com/yanolja_final/domain/user/controller/MyPageController.java, src/main/java/com/yanolja_final/domain/user/dto/request/UpdatePasswordRequest.java, src/main/java/com/yanolja_final/domain/user/entity/User.java, src/main/java/com/yanolja_final/domain/user/exception/DuplicatedCurrentPasswordException.java, src/main/java/com/yanolja_final/domain/user/facade/MyPageFacade.java, src/main/java/com/yanolja_final/domain/user/service/MyPageService.java, src/main/java/com/yanolja_final/global/exception/ErrorCode.java
-[Feature] PUT v1/my/password 비밀번호 수정
-비밀번호 변경 시 이전 비밀번호와 동일하면 예외 발생
#️⃣ 스크린샷
=> [Feature] PUT v1/my/password 비밀번호 수정

src/main/java/com/yanolja_final/domain/packages/controller/PackageController.java, src/main/java/com/yanolja_final/domain/packages/facade/PackageFacade.java, src/main/java/com/yanolja_final/domain/packages/repository/PackageRepository.java, src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
=> [feat] GET /v1/packages/top-purchases 가장 많이 구매한 패키지 목록

src/main/java/com/yanolja_final/domain/packages/controller/PackageController.java, src/main/java/com/yanolja_final/domain/packages/entity/Package.java, src/main/java/com/yanolja_final/domain/packages/facade/PackageFacade.java, src/main/java/com/yanolja_final/domain/packages/repository/PackageRepository.java, src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
closes #108 
- GET /v1/packages/similar-packages 유사한 패키지 구현
- 해시태그 순 정렬이 되는지 확인하기 위해 data.sql에 예시 해시태그 데이터를 넣었음
- 로직이 비효율적이여서 멘토님께 질문드렸고 답변오는대로 로직 개선 예정임
```json
{
"code": 200,
"data": {
"data": [
{
"packageId": 24031723749,
"imageUrl": "https://tourimage.interpark.com/product/tour/00161/B10/1000/B1016811_1_940.jpg",
"nationName": "베트남",
"title": "[다낭/자유여행] 시내중심 윙크리버사이드호텔 스탠다드룸+ 티웨이항공 3박5일",
"hashtags": [
"예시"
],
"minPrice": 559000,
"isWish": false,
"lodgeDays": 3,
"tripDays": 5
},
{
"packageId": 24011622550,
"imageUrl": "https://tourimage.interpark.com/product/tour/00161/A10/1000/A1041566_1_850.jpg",
"nationName": "베트남",
"title": "[코사무이/프리미엄 커플여행] 리츠칼튼 반자유 4박6일",
"hashtags": [],
"minPrice": 1940000,
"isWish": false,
"lodgeDays": 4,
"tripDays": 6
},
{
"packageId": 24011720149,
"imageUrl": …
```
=> [feat] GET /v1/packages/similar-packages 유사한 패키지

src/main/java/com/yanolja_final/domain/order/entity/Order.java, src/main/java/com/yanolja_final/domain/order/service/OrderService.java, src/main/java/com/yanolja_final/domain/packages/entity/PackageDepartureOption.java, src/main/java/com/yanolja_final/domain/packages/exception/PassedDepartureDateException.java, src/main/java/com/yanolja_final/domain/user/controller/MyPageController.java, src/main/java/com/yanolja_final/domain/user/dto/response/UpcomingPackageResponse.java, src/main/java/com/yanolja_final/domain/user/entity/User.java, src/main/java/com/yanolja_final/domain/user/facade/MyPageFacade.java, src/main/java/com/yanolja_final/domain/user/service/MyPageService.java, src/main/java/com/yanolja_final/global/exception/ErrorCode.java
###<문제원인 사진>
1. AService -> ARepository만 참고할 수 있도록 수정.
2. 기존 서비스 단에 있던 메서드 위치 수정(OrderSerivce -> Order // PackageService -> PackageDepartureOption)
3. Order Entity에 @OneToOne Jpa mapping을 적용하여, PackageDepartureDate availableDate를 생성하려고 하였으나, 기존  Long availableDateId가 기존 코드에 사용되어 지고 있어 수정 하였다가 다시 기존 코드로 반영하여 올렸습니다.
###<피드백 1>
###<피드백 1 / 수정 후>
###<피드백2>  ===> 해당 부분 availableDateID가 기존 창호님 코드와 물려 있어서 매핑 부분 수정하지 않고 우선 올렸습니다.
###<피드백 2/ 위의 피드백과 다른 방법으로 수정>
###<피드백3>
###<피드백3 / 수정 후>
###<피드백4>
###<피드백4 / 수정 후>
=> [Feature] GET /v1/my/upcoming-package 출발 일이 다가오는 패키지

src/main/java/com/yanolja_final/domain/poll/controller/PollController.java, src/main/java/com/yanolja_final/domain/poll/controller/response/PollResponse.java, src/main/java/com/yanolja_final/domain/poll/facade/PollFacade.java, src/main/java/com/yanolja_final/domain/poll/service/PollService.java, src/main/java/com/yanolja_final/global/config/security/SecurityConfig.java
- 메인페이지에 보여줄 찬반토론 기능 구현
- 찬반토론 관련 data.sql 변경 ( 줄바꿈 처리)
=> [Feature] GET v1/polls/main 메이페이지 찬반토론 기능 구현

src/main/java/com/yanolja_final/domain/wish/exception/DuplicateWishException.java, src/main/java/com/yanolja_final/domain/wish/service/WishService.java, src/main/java/com/yanolja_final/global/exception/ErrorCode.java
문제 사항 :
- 동일한 패키지에 좋아요르 중복 요청시 500에러 발생
변경 사항 :
- 동일한 패키지에 좋아요 중복 요청시 DuplicateWishException 발생
- http status : 500 -> 400
=> [refactor] 동일 패키지 좋아요 요청 예외 추가

src/main/java/com/yanolja_final/domain/packages/controller/HashtagController.java, src/main/java/com/yanolja_final/domain/packages/exception/HashtagNotFoundException.java, src/main/java/com/yanolja_final/domain/packages/repository/PackageQueryRepository.java, src/main/java/com/yanolja_final/domain/packages/service/HashtagService.java, src/main/java/com/yanolja_final/domain/packages/service/PackageService.java, src/main/java/com/yanolja_final/domain/search/controller/SearchController.java, src/main/java/com/yanolja_final/global/exception/ErrorCode.java
=> keword로 Hashtag를 찾지 못하는 경우 & sortBy 기본값 설정 & 예외 MSG변경 & Transactional설정

src/main/java/com/yanolja_final/domain/user/controller/MyPageController.java, src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
PR merge 이후, "서버 + 로컬 테스트 필요"
null = 허용 , 업데이트 X
"" = 허용X , 값을 입력하도록 메시지 안내
MyPageController에 @Valid 누락하였음 -> 수정 완료
=> [fix & Refactor] MyPage의 PATCH(내 정보) 와 PUT(비밀번호) 업데이트 수정

src/main/java/com/yanolja_final/domain/order/controller/request/OrderGuestInfoRequest.java, src/main/java/com/yanolja_final/domain/order/controller/response/OrderCreateResponse.java, src/main/java/com/yanolja_final/domain/order/controller/response/UserInfoResponse.java, src/main/java/com/yanolja_final/domain/order/exception/InvalidCancelFeeAgreementException.java, src/main/java/com/yanolja_final/domain/order/exception/NoGuestsException.java, src/main/java/com/yanolja_final/domain/order/facade/OrderFacade.java, src/main/java/com/yanolja_final/global/exception/ErrorCode.java
- 모든 사용자가 0명으로 예약을 진행하게 되는 경우
- 취소 수수료 false로 처리하는 경우
- 예약 진행시 사용자 번호 필드 추가
- 가장 간단한 if문으로 진행..
=> Order 수동 패키지에 따른 변경 사항

src/main/java/com/yanolja_final/domain/packages/facade/HashtagFacade.java, src/main/java/com/yanolja_final/domain/packages/repository/PackageRepository.java, src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
=> [Refactor] hashtag-search 검색 로직 변경

src/main/java/com/yanolja_final/domain/order/facade/OrderFacade.java, src/main/java/com/yanolja_final/domain/review/repository/ReviewRepository.java, src/main/java/com/yanolja_final/domain/review/service/ReviewService.java, src/main/java/com/yanolja_final/domain/wish/repository/WishRepository.java, src/main/java/com/yanolja_final/domain/wish/service/WishService.java
=> [Fix] 예약 내역 isWish/isReviewed 동작 안하는 오류 수정

src/main/java/com/yanolja_final/domain/packages/facade/HashtagFacade.java, src/main/java/com/yanolja_final/domain/packages/repository/PackageQueryRepository.java, src/main/java/com/yanolja_final/domain/packages/service/PackageService.java, src/main/java/com/yanolja_final/domain/theme/facade/ThemeFacade.java
=> [Refactor] hashtag-search search에서 사용하는 쿼리dsl 메소드 사용하게 변경
